name: splitio
description: Official plugin for split.io, the platform for controlled rollouts, which serves features to your users via feature flags to manage your complete customer experience.
version: 0.2.0-rc.1
homepage: https://split.io/
repository: https://github.com/splitio/flutter-sdk-plugin/tree/main/splitio/

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: splitio_android
      ios:
        default_package: splitio_ios

dependencies:
  flutter:
    sdk: flutter
  splitio_android: ^0.2.0-rc.1
  splitio_ios: ^0.2.0-rc.1
  splitio_platform_interface: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.1.4
