name: splitio_android
description: The official Android implementation of splitio Flutter plugin.
repository: https://github.com/splitio/flutter-sdk-plugin/tree/main/splitio_android
version: 1.1.0-rc.1

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: splitio
    platforms:
      android:
        package: io.split.splitio
        pluginClass: SplitioPlugin
        dartPluginClass: SplitioAndroid

dependencies:
  flutter:
    sdk: flutter
  splitio_platform_interface: ^2.1.0-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
