name: splitio_ios
description: The official iOS implementation of splitio Flutter plugin.
repository: https://github.com/splitio/flutter-sdk-plugin/tree/main/splitio_ios
version: 0.1.10-rc.1

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: splitio
    platforms:
      ios:
        pluginClass: SwiftSplitioPlugin
        dartPluginClass: SplitioIOS

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  splitio_platform_interface: ^1.5.0-rc.1
=======
  splitio_platform_interface: #^1.4.0
    path: ../splitio_platform_interface
>>>>>>> development

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
