name: splitio_ios
publish_to: 'none'
description: The official iOS implementation of splitio Flutter plugin.
repository: https://github.com/splitio/flutter-sdk-plugin/tree/main/splitio_ios
version: 0.2.0-rc.1

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: splitio
    platforms:
      ios:
        pluginClass: SwiftSplitioPlugin
        dartPluginClass: SplitioIOS

dependencies:
  flutter:
    sdk: flutter
  splitio_platform_interface: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
